#!/usr/bin/env python3
"""Compare two WCT field-response files.

    fr_compare.py A.json.bz2 B.json.bz2 OUTDIR --tag TAG [--labels a,b]

When B is the hidden truth this belongs to the *scoring* side of the workflow
(design.md, "Hidden-truth discipline"): its outputs describe the target for
the note and must never be inputs to a fit.

Writes OUTDIR/fr-TAG.pdf (per plane: impact-averaged central-wire current,
and its running integral) and OUTDIR/fr-TAG.tex (LaTeX macros named
\\TAG...; TAG must be letters only).
"""
import argparse
import bz2
import json
from pathlib import Path

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

PLANES = "UVW"


def load_fr(path):
    """WCT FieldResponse -> dict(period, planes=[(pitch, pitchpos, current)])."""
    fr = json.load(bz2.open(path) if str(path).endswith(".bz2") else open(path))
    fr = fr.get("FieldResponse", fr)
    planes = []
    for p in fr["planes"]:
        p = p.get("PlaneResponse", p)
        paths = [q.get("PathResponse", q) for q in p["paths"]]
        pos = np.array([q["pitchpos"] for q in paths])
        cur = np.array([np.asarray(q["current"].get("array", q["current"])["elements"])
                        for q in paths])
        order = np.argsort(pos, kind="stable")
        planes.append((p["pitch"], pos[order], cur[order]))
    return dict(period=fr["period"], speed=fr["speed"], origin=fr["origin"],
                planes=planes)


def central(pitch, pos, cur):
    """Paths whose impact lies within the central wire's half pitch."""
    sel = np.abs(pos) <= 0.5 * pitch + 1e-6
    return pos[sel], cur[sel]


def macro(name, value, fmt):
    return f"\\newcommand{{\\{name}}}{{{value:{fmt}}}}"


def main(fa, fb, outdir, tag, labels=("nominal", "truth")):
    if not tag.isalpha():
        raise ValueError(f"tag must be letters only: {tag}")
    outdir = Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    a, b = load_fr(fa), load_fr(fb)
    T = a["period"]
    lines = [f"% generated by {Path(__file__).name}; do not edit"]
    lines.append(macro(f"{tag}PeriodNs", T, ".0f"))
    lines.append(macro(f"{tag}Npaths", len(a["planes"][0][1]), "d"))

    fig, axes = plt.subplots(2, 3, figsize=(11, 5.5), sharex=True)
    for ip, (pa, pb) in enumerate(zip(a["planes"], b["planes"])):
        pitch, posa, cura = pa
        _, posb, curb = pb
        if not np.allclose(posa, posb):
            raise ValueError(f"plane {ip}: impact positions differ")
        _, ca = central(pitch, posa, cura)
        _, cb = central(pitch, posb, curb)
        qa, qb = ca.sum(1) * T, cb.sum(1) * T        # per-path net charge [e]
        # "dead" paths: identically zero where the other file is not
        nzero = int(np.sum((np.abs(cura).max(1) == 0) & (np.abs(curb).max(1) > 0)))
        rel = np.sqrt(np.mean((cura - curb) ** 2)) / np.abs(cura).max()
        P = PLANES[ip]
        lines += [macro(f"{tag}Pitch{P}", pitch, ".2f"),
                  macro(f"{tag}QA{P}", np.median(qa), ".3f"),
                  macro(f"{tag}QB{P}", np.median(qb), ".3f"),
                  macro(f"{tag}PeakA{P}", np.abs(cura).max() * 1e3, ".3f"),
                  macro(f"{tag}PeakB{P}", np.abs(curb).max() * 1e3, ".3f"),
                  macro(f"{tag}RelRms{P}", rel, ".1e"),
                  macro(f"{tag}ZeroA{P}", nzero, "d")]
        t = np.arange(cura.shape[1]) * T / 1000.0     # us
        axes[0, ip].plot(t, ca.mean(0), label=labels[0])
        axes[0, ip].plot(t, cb.mean(0), label=labels[1], ls="--")
        axes[1, ip].plot(t, np.cumsum(ca.mean(0)) * T)
        axes[1, ip].plot(t, np.cumsum(cb.mean(0)) * T, ls="--")
        axes[0, ip].set_title(f"plane {P}, pitch {pitch:g} mm")
        axes[1, ip].set_xlabel(r"time [$\mu$s]")
    axes[0, 0].set_ylabel("current, central wire\n(impact average)")
    axes[1, 0].set_ylabel("running charge [e]")
    axes[0, 0].legend(frameon=False)
    # zoom on where the responses live: the last few tens of us
    big = [np.abs(c).max(0) > 1e-3 * np.abs(c).max() for _, _, c in a["planes"] + b["planes"]]
    first = min(np.argmax(m) for m in big) * T / 1000.0
    last = max(len(m) - np.argmax(m[::-1]) for m in big) * T / 1000.0
    for x in axes[1]:
        x.set_xlim(max(0.0, first - 5.0), min(t[-1], last + 10.0))
    fig.tight_layout()
    fig.savefig(outdir / f"fr-{tag}.pdf")
    (outdir / f"fr-{tag}.tex").write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("a")
    ap.add_argument("b")
    ap.add_argument("outdir")
    ap.add_argument("--tag", required=True)
    ap.add_argument("--labels", default="nominal,truth")
    x = ap.parse_args()
    main(x.a, x.b, x.outdir, x.tag, tuple(x.labels.split(",")))
