#!/usr/bin/env python3
"""Look at WCT frame files from sim-laser.jsonnet.

    frame_view.py OUT.pdf FRAMES.npz[:label[:shift]] [FRAMES.npz[:label[:shift]] ...]
                  [--event N] [--anodes 0,2] [--tex OUT.tex --tag TAG]

Top rows: baseline-subtracted ADC of the first file, one panel per plane per
anode, zoomed on the activity.  Bottom row: for each plane of the first
anode, the waveform on its busiest channel from every file, overlaid.
Channels are split into planes by the WCT channel numbering of PDHD
(per anode: 800 U, 800 V, 960 W).

A shift (ticks, may be fractional) moves that file's frames later in time
before plotting, e.g. to undo a known time-origin offset.

With --tex, writes macros \\TAG{Anode}{Plane}{Peak,Trough} (ADC, first file).
"""
import argparse
from pathlib import Path

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

PLANES = "UVW"
SPLIT = (800, 1600)          # U | V | W within an anode's 2560 channels


def shift_ticks(adc, s):
    if not s:
        return adc
    n = adc.shape[1]
    k = np.fft.rfftfreq(n)
    return np.fft.irfft(np.fft.rfft(adc, axis=1) * np.exp(-2j * np.pi * k * s), n, axis=1)


def load(path, event, anode, shift=0.0):
    """(channels, baseline-subtracted adc float array) for one anode/event."""
    f = np.load(path)
    key = f"frame_orig{anode}_{event}"
    if key not in f:
        have = sorted(k for k in f if k.startswith(f"frame_orig{anode}_"))
        raise KeyError(f"{key} not in {path}; have {have[:3]}...")
    adc = f[key].astype(float)
    ch = f[f"channels_orig{anode}_{event}"]
    adc -= np.median(adc, axis=1, keepdims=True)
    return ch, shift_ticks(adc, shift)


def planes(ch, adc):
    rel = ch - ch.min()
    cuts = [rel < SPLIT[0], (rel >= SPLIT[0]) & (rel < SPLIT[1]), rel >= SPLIT[1]]
    return [(ch[c], adc[c]) for c in cuts]


def window(adc, pad=50):
    """Tick range around activity."""
    act = np.flatnonzero(np.abs(adc).max(0) > 5)
    if not len(act):
        return 0, adc.shape[1]
    return max(0, act[0] - pad), min(adc.shape[1], act[-1] + pad)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("output")
    ap.add_argument("frames", nargs="+")
    ap.add_argument("--event", type=int, default=None, help="default: first")
    ap.add_argument("--anodes", default="0,2")
    ap.add_argument("--tex")
    ap.add_argument("--tag", default="fv")
    a = ap.parse_args()
    files = []
    for spec in a.frames:
        parts = spec.split(":")
        files.append((parts[0], parts[1] if len(parts) > 1 else Path(parts[0]).stem,
                      float(parts[2]) if len(parts) > 2 else 0.0))
    anodes = [int(x) for x in a.anodes.split(",")]
    if a.event is None:
        keys = [k for k in np.load(files[0][0]) if k.startswith(f"frame_orig{anodes[0]}_")]
        a.event = min(int(k.rsplit("_", 1)[1]) for k in keys)

    fig, ax = plt.subplots(len(anodes) + 1, 3, figsize=(12, 3.3 * (len(anodes) + 1)))
    lines = [f"% generated by {Path(__file__).name}; do not edit"]
    names = {0: "Zero", 1: "One", 2: "Two", 3: "Three"}
    for ia, anode in enumerate(anodes):
        ch, adc = load(files[0][0], a.event, anode)
        for ip, (pc, pa) in enumerate(planes(ch, adc)):
            t0, t1 = window(pa)
            v = max(5.0, np.percentile(np.abs(pa[:, t0:t1]), 99.9))
            ax[ia, ip].imshow(pa[:, t0:t1].T, aspect="auto", origin="lower",
                              cmap="RdBu_r", vmin=-v, vmax=v,
                              extent=[pc.min(), pc.max(), t0, t1])
            ax[ia, ip].set_title(f"anode {anode} {PLANES[ip]}  [{pa.min():.0f}, {pa.max():.0f}] ADC",
                                 fontsize=9)
            lines += [f"\\newcommand{{\\{a.tag}{names[anode]}{PLANES[ip]}Peak}}{{{pa.max():.0f}}}",
                      f"\\newcommand{{\\{a.tag}{names[anode]}{PLANES[ip]}Trough}}{{{pa.min():.0f}}}"]
        ax[ia, 0].set_ylabel("tick")
    anode = anodes[0]
    ch0, adc0 = load(files[0][0], a.event, anode)
    for ip, (pc, pa) in enumerate(planes(ch0, adc0)):
        busiest = int(np.argmax(np.abs(pa).max(1)))
        t0, t1 = window(pa[busiest:busiest + 1], pad=40)
        for path, label, sh in files:
            c, x = load(path, a.event, anode, sh)
            _, xa = planes(c, x)[ip]
            ax[-1, ip].plot(np.arange(t0, t1), xa[busiest, t0:t1], label=label, lw=1)
        ax[-1, ip].set_title(f"anode {anode} {PLANES[ip]} channel {pc[busiest]}", fontsize=9)
        ax[-1, ip].set_xlabel("tick")
    ax[-1, 0].set_ylabel("ADC - baseline")
    ax[-1, 0].legend(frameon=False, fontsize=8)
    fig.suptitle(f"event {a.event}", fontsize=10)
    fig.tight_layout()
    fig.savefig(a.output)
    if a.tex:
        Path(a.tex).write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
