#!/usr/bin/env python3
"""Where the recorded laser shots go, and the phase space they cover.

    laser_coverage.py WIRES OUTDIR CSV [CSV ...] --anode A --control C
                      [--shift dx,dy,dz] [--flip fx,fy,fz]

For each shot, clip the beam to the active boxes of the target and control
anodes, both as recorded and after moving the shots (``--shift`` translates
the port, ``--flip`` multiplies direction components), and report the angles that matter to the field response: for each
wire plane, the track angle in the plane spanned by the drift direction and
that plane's pitch direction (0 = along the drift, 90 deg = isochronous), and
the angle to the wire direction within the wire plane.

Writes OUTDIR/laser-coverage.pdf and OUTDIR/laser-coverage.tex (macros).
"""
import argparse
from pathlib import Path

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

import laser
import wires
from laser_depos import clip_to_box, floats

PLANES = "UVW"


def clip_all(origins, dirs, lo, hi):
    """(N,2,3) segment endpoints inside the box, NaN where missed; lengths."""
    seg = np.full((len(origins), 2, 3), np.nan)
    for i, (o, d) in enumerate(zip(origins, dirs)):
        c = clip_to_box(o, d, lo, hi)
        if c is not None:
            s0, s1, u = c
            seg[i] = o + s0 * u, o + s1 * u
    return seg, np.linalg.norm(seg[:, 1] - seg[:, 0], axis=1)


def plane_angles(dirs, planes):
    """Per plane: angle in the (drift, pitch) plane and angle to the wire, deg."""
    out = []
    xhat = np.array([1.0, 0, 0])
    for p in planes:
        w = p["dir"]
        pitch = np.cross(xhat, w)
        pitch /= np.linalg.norm(pitch)
        thp = np.degrees(np.arctan2(np.abs(dirs @ pitch), np.abs(dirs @ xhat)))
        inplane = dirs - np.outer(dirs @ xhat, xhat)
        inplane /= np.linalg.norm(inplane, axis=1)[:, None]
        thw = np.degrees(np.arccos(np.clip(np.abs(inplane @ w), 0, 1)))
        out.append((thp, thw))
    return out


def macro(name, value, fmt):
    return f"\\newcommand{{\\{name}}}{{{value:{fmt}}}}"


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("wires")
    ap.add_argument("outdir")
    ap.add_argument("csv", nargs="+")
    ap.add_argument("--anode", type=int, default=0)
    ap.add_argument("--control", type=int, default=2)
    ap.add_argument("--shift", default="0,0,0", type=lambda t: floats(t, 3))
    ap.add_argument("--flip", default="1,1,1", type=lambda t: floats(t, 3))
    a = ap.parse_args()
    out = Path(a.outdir)
    out.mkdir(parents=True, exist_ok=True)

    store = wires.load(a.wires)
    box_t = wires.active_box(store, a.anode)
    box_c = wires.active_box(store, a.control)
    planes = wires.active_face(store, a.anode)

    runs = []
    for path in a.csv:
        c = laser.read_csv(path)
        o, d = c["origin"], c["direction"]
        om, dm = laser.transform(o, d, a.shift, a.flip)
        _, len_raw = clip_all(o, d, *box_t)               # target, as recorded
        seg_rc, _ = clip_all(o, d, *box_c)                # control, as recorded
        seg_t, len_t = clip_all(om, dm, *box_t)           # target, moved
        seg_c, len_c = clip_all(om, dm, *box_c)           # control, moved
        runs.append(dict(name=Path(path).stem.split("_")[4], o=o, om=om,
                         seg_t=seg_t, len_t=len_t, seg_c=seg_c, len_c=len_c,
                         seg_rc=seg_rc, hit_raw=np.mean(len_raw > 0),
                         ang=plane_angles(dm, planes)))

    lines = [f"% generated by {Path(__file__).name}; do not edit",
             macro("lzShiftZcm", a.shift[2] / 10, ".1f"),
             macro("lzFlipZ", "yes" if a.flip[2] < 0 else "no", "s")]
    tags = "AB"
    for tag, r in zip(tags, runs):
        hit = r["len_t"] > 0
        lines += [macro(f"lz{tag}Nshots", len(r["o"]), "d"),
                  macro(f"lz{tag}PortX", r["o"][:, 0].mean() / 10, ".1f"),
                  macro(f"lz{tag}PortY", r["o"][:, 1].mean() / 10, ".1f"),
                  macro(f"lz{tag}PortZ", r["o"][:, 2].mean() / 10, ".1f"),
                  macro(f"lz{tag}HitRaw", 100 * r["hit_raw"], ".0f"),
                  macro(f"lz{tag}HitMoved", 100 * hit.mean(), ".0f"),
                  macro(f"lz{tag}HitControl", 100 * np.mean(r["len_c"] > 0), ".0f"),
                  macro(f"lz{tag}LenMedcm", np.median(r["len_t"][hit]) / 10 if hit.any() else 0, ".0f")]
        for P, (thp, thw) in zip(PLANES, r["ang"]):
            lines += [macro(f"lz{tag}Thp{P}min", thp.min(), ".0f"),
                      macro(f"lz{tag}Thp{P}max", thp.max(), ".0f")]
    (out / "laser-coverage.tex").write_text("\n".join(lines) + "\n")

    fig, ax = plt.subplots(2, 2, figsize=(11, 8))
    for lo, hi, lab in [(*box_t, f"anode {a.anode}"), (*box_c, f"anode {a.control}")]:
        for k, (i, j) in enumerate([(2, 1), (2, 0)]):
            ax[0, k].add_patch(plt.Rectangle((lo[i], lo[j]), hi[i] - lo[i], hi[j] - lo[j],
                                             fill=False, lw=1, color="0.4"))
            ax[0, k].text(lo[i] + 50, hi[j] - 250, lab, color="0.4", fontsize=8)
    for n, r in enumerate(runs):
        col = f"C{n}"
        for seg, ls, alpha in [(r["seg_rc"], ":", 0.3), (r["seg_c"], "-", 0.5),
                               (r["seg_t"], "-", 0.5)]:
            step = max(1, len(seg) // 150)
            for s in seg[::step]:
                if np.isnan(s).any():
                    continue
                ax[0, 0].plot(s[:, 2], s[:, 1], ls, color=col, lw=0.5, alpha=alpha)
                ax[0, 1].plot(s[:, 2], s[:, 0], ls, color=col, lw=0.5, alpha=alpha)
        ax[0, 0].plot(*r["o"][:, [2, 1]].mean(0), "o", color=col, label=r["name"])
        ax[0, 0].plot(*r["om"][:, [2, 1]].mean(0), "s", color=col, mfc="none")
        for P, (thp, thw), ls in zip(PLANES, r["ang"], ["-", "--", ":"]):
            ax[1, 0].hist(thp, bins=90, range=(0, 90), histtype="step", ls=ls, color=col,
                          label=f"{r['name']} {P}")
            ax[1, 1].hist(thw, bins=90, range=(0, 90), histtype="step", ls=ls, color=col,
                          label=f"{r['name']} {P}")
    ax[0, 0].set(xlabel="z [mm]", ylabel="y [mm]",
                 title="wire-plane view (dotted: recorded, solid: moved)")
    ax[0, 1].set(xlabel="z [mm]", ylabel="x [mm]", title="top view")
    ax[0, 0].legend(fontsize=8, frameon=False)
    ax[1, 0].set(xlabel="angle from drift in (drift, pitch) plane [deg]",
                 ylabel="shots", yscale="log")
    ax[1, 1].set(xlabel="angle to wire within wire plane [deg]", yscale="log")
    ax[1, 0].legend(fontsize=7, frameon=False, ncol=2)
    for x in ax[0]:
        x.set_aspect("equal", adjustable="datalim")
    fig.tight_layout()
    fig.savefig(out / "laser-coverage.pdf")


if __name__ == "__main__":
    main()
