#!/usr/bin/env python3
"""Central-wire currents path by path: several WCT field-response files.

    path_compare.py OUT.pdf --tex OUT.tex --tag TAG FR[:label[:shift_us]] ...

Rows: planes W and V; columns: the six impact positions 0 .. 0.5 pitch.  A
shift (us) moves that file's currents later, e.g. to undo a drift-speed
offset.  Macros \\TAG{Plane}{Impact}{File} give each path's net charge [e]
(Impact 0..5 as A..F, File as A, B, ... in the order given).

When one file is the hidden truth this is a scoring-side diagnostic.
"""
import argparse
from pathlib import Path

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from fr_compare import load_fr

LETTERS = "ABCDEF"


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("output")
    ap.add_argument("frs", nargs="+")
    ap.add_argument("--tex", required=True)
    ap.add_argument("--tag", required=True)
    ap.add_argument("--xlim", default="55,85", help="us")
    a = ap.parse_args()
    specs = []
    for s in a.frs:
        p = s.split(":")
        specs.append((p[0], p[1] if len(p) > 1 else Path(p[0]).stem,
                      float(p[2]) if len(p) > 2 else 0.0))
    frs = [(load_fr(path), lab, sh) for path, lab, sh in specs]
    xlim = [float(x) for x in a.xlim.split(",")]

    lines = [f"% generated by {Path(__file__).name}; do not edit"]
    fig, ax = plt.subplots(2, 6, figsize=(16, 5.5))
    for row, ip in enumerate([2, 1]):
        for k in range(6):
            for ifr, (fr, lab, sh) in enumerate(frs):
                pitch, pos, cur = fr["planes"][ip]
                j = int(np.argmin(np.abs(pos + 0.1 * k * pitch)))   # pitchpos -k p/10
                T = fr["period"] / 1000.0
                t = np.arange(cur.shape[1]) * T + sh
                ax[row, k].plot(t, cur[j], ["-", "--", ":", "-."][ifr % 4], label=lab)
                q = cur[j].sum() * fr["period"]
                lines.append(f"\\newcommand{{\\{a.tag}{'UVW'[ip]}{LETTERS[k]}{LETTERS[ifr]}}}"
                             f"{{{q:+.3f}}}")
            ax[row, k].set_xlim(*xlim)
            ax[row, k].set_title(f"{'UVW'[ip]}, impact {0.1 * k:.1f} pitch", fontsize=9)
        ax[row, 0].set_ylabel("current [WCT units]")
    for k in range(6):
        ax[1, k].set_xlabel(r"time [$\mu$s]")
    ax[0, 0].legend(fontsize=7, frameon=False)
    fig.tight_layout()
    fig.savefig(a.output)
    Path(a.tex).write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
