#!/usr/bin/env python3
"""LaTeX macros for the note's Setup section from config.yaml (and results).

    setup_macros.py config.yaml VFLOAT.txt OUT.tex
"""
import sys
from pathlib import Path

import yaml


def main(cfg_path, vfloat_path, out):
    c = yaml.safe_load(open(cfg_path))
    m = {
        "cfgAnode": c["anode"],
        "cfgControl": c["control_anode"],
        "cfgGain": c["sim"]["gain_mV_fC"],
        "cfgNoise": c["fit"]["noise_adc"],
        "cfgFitStride": c["fit"]["stride"],
        "cfgHoldFirst": c["fit"]["holdout_first"],
        "cfgLaserStride": c["laser"]["stride"],
        "cfgStep": c["laser"]["step_mm"],
        "cfgDqdx": c["laser"]["dqdx_per_mm"],
        "cfgMesh": abs(c["bad_apa"]["mesh_y_mm"]),   # depth below W
        "cfgVfloat": f"{float(Path(vfloat_path).read_text()):.1f}",
        "cfgNoiseOn": "on" if c["sim"]["noise"] else "off",
        "cfgFluct": "on" if c["sim"]["fluctuate"] else "off",
    }
    lines = [f"% generated by {Path(__file__).name}; do not edit"]
    lines += [f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in m.items()]
    Path(out).write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main(*sys.argv[1:4])
