#!/usr/bin/env python
"""Turn a ``FIREP_PERF`` JSONL log into the LaTeX table the note includes.

  scripts/perf_table.py runs/perf.jsonl docs/figs/perf.tex

Writes a ``tabular`` plus a few ``\\newcommand`` macros, so the note quotes the
timings of the run that actually produced its figures.
"""

from __future__ import annotations

import os
import re
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src"))

from firep import perf  # noqa: E402

LABEL = {
    "train": "train", "response": "response", "signal": "signal",
    "sample": "sample", "figs": "figures", "doc": "document", "stage": "stage",
}


def _fmt_time(s: float) -> str:
    if s >= 3600:
        return f"{s / 3600:.2f} h"
    if s >= 60:
        return f"{s / 60:.1f} min"
    return f"{s:.1f} s"


def _tex(text: str) -> str:
    return str(text).replace("_", r"\_").replace("&", r"\&")


STUB_MACROS = ("valPerfWall", "valPerfCpu", "valPerfSpeedup", "valPerfCores",
               "valPerfCpuModel", "valPerfPeakRss", "valPerfTrainWall",
               "valPerfTrainStage", "valPerfNSolves", "valPerfTorch")


def stub(out: str, why: str = "not measured") -> None:
    """Keep the note buildable when no timing log is around."""
    with open(out, "w") as fp:
        fp.write("% Generated by scripts/perf_table.py -- do not edit.\n")
        fp.write(f"\\newcommand{{\\perfTable}}{{\\emph{{{why}}}}}\n")
        for name in STUB_MACROS:
            fp.write(f"\\newcommand{{\\{name}}}{{--}}\n")


def build(records: list[dict]) -> tuple[str, dict]:
    host = next((r for r in records if r["kind"] == "host"), None)
    steps = [r for r in records if r["kind"] not in ("host", "stage")]
    stages = [r for r in records if r["kind"] == "stage"]
    steps.sort(key=lambda r: r.get("started", 0.0))

    def short(r):
        """A step label that fits: the config name adds width, not meaning."""
        d = r.get("detail", {})
        if r["kind"] != "train":
            return r["name"]
        verb = "train" if d.get("steps") else "warm start"
        who = d.get("problem", "")
        m = re.search(r"\(([^)]*)\)", r["name"])
        return f"{verb} {who}" + (f" ({m.group(1)})" if m else "")

    rows = []
    for r in steps:
        d = r.get("detail", {})
        note = []
        if d.get("steps"):
            note.append(f"{d['steps']:,} steps")
        elif r["kind"] == "train":
            note.append("no gradient steps")
        if "conductors" in d:
            note.append(f"{d['conductors']} wires")
        if "impacts" in d and "wires" in d and r["kind"] == "response":
            note.append(f"{d['impacts']}$\\times${d['wires']}$\\times${d['ticks']}")
        if "groups" in d:
            note.append(f"{d['groups']:,} groups")
        if "grid" in d:
            note.append(d["grid"])
        if "figures" in d:
            note.append(f"{d['figures']} figures")
        eff = r["cpu_s"] / r["wall_s"] if r["wall_s"] > 0 else 0.0
        rows.append((_tex(short(r)), ", ".join(note), _fmt_time(r["wall_s"]),
                     _fmt_time(r["cpu_s"]), f"{eff:.1f}", f"{r['rss_mb']:.0f}"))

    wall = sum(r["wall_s"] for r in steps)
    cpu = sum(r["cpu_s"] for r in steps)
    rss = max((r["rss_mb"] for r in steps), default=0.0)
    train = [r for r in steps if r["kind"] == "train"]
    train_wall = sum(r["wall_s"] for r in train)
    train_stage = next((r for r in stages if r["name"].startswith("training")), None)

    out = [r"\begin{tabular}{@{}lllrrr@{}}", r"\toprule",
           r"step & size & wall & CPU & CPU/wall & RSS [MB] \\",
           r"\midrule"]
    for row in rows:
        out.append(" & ".join(row) + r" \\")
    out.append(r"\midrule")
    out.append(" & ".join(("total", "", _fmt_time(wall), _fmt_time(cpu),
                           f"{cpu / wall:.1f}" if wall else "--",
                           f"{rss:.0f}")) + r" \\")
    if train_stage:
        out.append(" & ".join(
            (r"\quad\emph{four solves, concurrent}", "",
             _fmt_time(train_stage["wall_s"]), "", "", "")) + r" \\")
    out.append(r"\bottomrule")
    out.append(r"\end{tabular}")

    macros = {
        "valPerfWall": _fmt_time(wall),
        "valPerfCpu": _fmt_time(cpu),
        "valPerfPeakRss": f"{rss:.0f}",
        "valPerfTrainWall": _fmt_time(train_wall),
        "valPerfNSolves": str(len(train)),
    }
    if train_stage and train_stage["wall_s"] > 0:
        macros["valPerfTrainStage"] = _fmt_time(train_stage["wall_s"])
        macros["valPerfSpeedup"] = f"{train_wall / train_stage['wall_s']:.1f}"
    if host:
        macros["valPerfCores"] = str(host["detail"].get("cores", "--"))
        macros["valPerfCpuModel"] = _tex(host["detail"].get("cpu", "--"))
        macros["valPerfTorch"] = _tex(host["detail"].get("torch", "--"))
    return "\n".join(out), macros


def main(perf_path: str, out_path: str) -> int:
    if not os.path.exists(perf_path):
        stub(out_path, "no timing log found")
        print(f"wrote {out_path} (stub: {perf_path} missing)")
        return 0
    records = perf.load(perf_path)
    if not records:
        stub(out_path, "timing log empty")
        return 0
    table, macros = build(records)
    for name in STUB_MACROS:
        macros.setdefault(name, "--")
    with open(out_path, "w") as fp:
        fp.write("% Generated by scripts/perf_table.py -- do not edit.\n")
        fp.write("\\newcommand{\\perfTable}{%\n" + table + "%\n}\n")
        for k, v in sorted(macros.items()):
            fp.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")
    print(f"wrote {out_path} from {len(records)} records")
    return 0


if __name__ == "__main__":
    args = sys.argv[1:]
    raise SystemExit(main(args[0] if args else "runs/perf.jsonl",
                          args[1] if len(args) > 1 else "docs/figs/perf.tex"))
